### ISSUE TITLE
FE - Landing Page

### ISSUE THREAD

**Issue by heyitsmattox** [Los-Terremotos/GreenPets#19]
Landing Page Requirements:

Route https://localhost:3000 will be our primary splash screen

- Include features regarding the application
- Middle section with ____ info 
- Team section (include all the devs/info)
- footer

NavBar
1. Getting Started
  a) This route will route to the main application route where user can insert their location
2. Login portal
3. Roadmap
 a) Include a timeline / visual of upcoming features

**Comment by KP824** [comment]
Completed. Well done Matt!
