### ISSUE TITLE
FE - Figma Spec for splash page

### ISSUE THREAD

**Issue by heyitsmattox** [Los-Terremotos/GreenPets#20]
Create a UI spec for the splash page. Will share with team once done.

**Comment by heyitsmattox** [comment]
Waiting on approval on [spec](https://www.figma.com/file/dGYOIuRu7hDlWbH0hL3Xc0/Green-Pets?type=whiteboard&node-id=0-1&t=98zMvNODUavIDaOy-0).



![Image](https://github.com/Los-Terremotos/GreenPets/assets/90209258/328e7131-b9c5-48dd-9103-5aa13226467a)

**Comment by KP824** [comment]
This is beautiful! Great job Matt!
