### ISSUE TITLE
FE - Build 2nd Page (Get Started)

### ISSUE THREAD

**Issue by stephanie-115** [Los-Terremotos/GreenPets#21]
- Ask questions to request user inputs

1. Do you prefer indoor or outdoor plants?
2. How green is your thumb?
- A) Forest green (4 value)
- B) Mint Green (3 value)
- C) Brown (2 value)

- Implement GraphQL query to pass on user inputs
- Response from query is saved into state

- Once response is successful, reroute user to Results page

**Comment by heyitsmattox** [comment]
@KP824 @crisdevs this is the page/route when a user clicks `get started` correct?

**Comment by crisdevs** [comment]
The Questionnaire page/ get started page has been built out. If there are any bugs that we find or any modifications needed afterwards we can always make a new ticket. Will close for now.
