### ISSUE TITLE
FE - Results Modal Styling

### ISSUE THREAD

**Issue by stephanie-115** [Los-Terremotos/GreenPets#42]
To complete this ticket, use the mock data located in `client/src/mockData/plantDetails` and `client/src/mockData/plantDetails2`

Conditionally render the display values. If the value is null, the display should not render for that specific field.

Note: Change the display names shown to the user as you see fit.

Display the following fields (in the data object):
- common_name (value = string)
- scientific_name (value = string)
- origin (value = array)
- type (value = string)
- watering (value = string)
- watering_general_benchmark.value (value = number)
- watering_general_benchmark.unit (value = string)
- plant_anatomy (value = array of objects. Each object has a key 'part' with a string value and a key 'color' with an array value)
- sunlight (value = array)
- pruning_month (value = array)
- maintenance (value = string)
- care-guides (value = string **URL to API) --> we may not want this ? 
- drought_tolerant (value = boolean)
- thorny (value = boolean)
- indoor (value = boolean)
- flowers (value = boolean *combine with fruits*)
- fruits (value = boolean *combine with flowers*)
- poisonous_to_humans (value = number) -- possibly come up with an array of strings that will render a specific string depending on the value given (ex: 0 would render 'No')
- poisonous_to_pets (value = number)-- possibly come up with an array of strings that will render a specific string depending on the value given (ex: 0 would render 'No')
- description (value = string)-- paragraph
- default_image.thumbnail (value = string (url))

**Comment by KP824** [comment]
Progress update:

- Clicking "More Info" button on each plant card will now successfully render a modal
- Current modal displays newly updated field types, added to PlantInfo types
- Left column of modal has a navigation tab that contains several categories where the plant details are grouped and organized to show similar data
- Currently need to update logic to correctly render boolean values for the available fields
- Need to implement logic to not render or display any fields that return empty or have undefined values
- Need to update styling for the data rendered

![Image](https://github.com/Los-Terremotos/GreenPets/assets/112226540/f8176b20-6363-4c7c-8685-d19853006afc)
